### ISSUE TITLE
replace node-sass with sass (node-sass crashes too much)

### ISSUE THREAD

**Issue by trusktr** [cruise-automation/webviz#609]
I _always_ have issues with `node-sass` (node-gyp issues). Using the `sass` package is the way to go because it is implemented in JS and so does not require native extensions.

I just tried `npm run bootstrap` after cloning the repo, and it failed with errors:

<details><summary>errors (click to expand)</summary>

Better to get rid of the burden. The `sass` package always works perfectly!

```
In file included from ../../nan/nan_converters.h:67,
                 from ../../nan/nan.h:221,
                 from ../src/binding.cpp:1:
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
../../nan/nan_converters_43_inl.h:18:49: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
   18 |       val->To ## TYPE(isolate->GetCurrentContext())                            \
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                 |
      |                                                 v8::Local<v8::Context>
../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
   22 | X(Boolean)
      | ^
In file included from /home/trusktr/.node-gyp/14.15.5/include/node/node.h:67,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:2848:37: note:   initializing argument 1 of ‘v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate*) const’
 2848 |   Local<Boolean> ToBoolean(Isolate* isolate) const;
      |                            ~~~~~~~~~^~~~~~~
In file included from ../../nan/nan_converters.h:67,
                 from ../../nan/nan.h:221,
                 from ../src/binding.cpp:1:
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:
../../nan/nan_converters_43_inl.h:37:55: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
   37 |   return val->NAME ## Value(isolate->GetCurrentContext());                     \
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                       |
      |                                                       v8::Local<v8::Context>
../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
   40 | X(bool, Boolean)
      | ^
In file included from /home/trusktr/.node-gyp/14.15.5/include/node/node.h:67,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:2858:30: note:   initializing argument 1 of ‘bool v8::Value::BooleanValue(v8::Isolate*) const’
 2858 |   bool BooleanValue(Isolate* isolate) const;
      |                     ~~~~~~~~~^~~~~~~
In file included from ../../nan/nan_new.h:189,
                 from ../../nan/nan.h:222,
                 from ../src/binding.cpp:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan_implementation_12_inl.h:103:42: error: cannot convert ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
  103 |   return scope.Escape(v8::Function::New( isolate
      |                                          ^~~~~~~
      |                                          |
      |                                          v8::Isolate*
In file included from /home/trusktr/.node-gyp/14.15.5/include/node/node.h:67,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:4446:22: note:   initializing argument 1 of ‘static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)’
 4446 |       Local<Context> context, FunctionCallback callback,
      |       ~~~~~~~~~~~~~~~^~~~~~~
In file included from ../src/binding.cpp:1:
../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
../../nan/nan.h:1064:76: error: cannot convert ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
 1064 | ::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
      |                                             ~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                    |
      |                                                                    v8::Isolate*

In file included from /home/trusktr/.node-gyp/14.15.5/include/node/node.h:67,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:2811:22: note:   initializing argument 1 of ‘v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const’
 2811 |       Local<Context> context) const;
      |       ~~~~~~~~~~~~~~~^~~~~~~
In file included from ../src/binding.cpp:1:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1855:64: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, const v8::Local<v8::Value>&)’
 1855 |     New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
      |                                                                ^
In file included from /home/trusktr/.node-gyp/14.15.5/include/node/node.h:67,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../src/binding.cpp:1:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1861:42: error: no matching function for call to ‘v8::Object::Set(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)’
 1861 |     New(persistentHandle)->Set(key, value);
      |                                          ^
In file included from /home/trusktr/.node-gyp/14.15.5/include/node/node.h:67,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../src/binding.cpp:1:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1867:44: error: no matching function for call to ‘v8::Object::Set(uint32_t&, const v8::Local<v8::Value>&)’
 1867 |     New(persistentHandle)->Set(index, value);
      |                                            ^
In file included from /home/trusktr/.node-gyp/14.15.5/include/node/node.h:67,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../src/binding.cpp:1:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../../nan/nan.h:1873:61: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::String>)’
 1873 |         New(persistentHandle)->Get(New(key).ToLocalChecked()));
      |                                                             ^
In file included from /home/trusktr/.node-gyp/14.15.5/include/node/node.h:67,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
 3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
 3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
In file included from ../src/binding.cpp:1:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String>&) const’:
../../nan/nan.h:1879:55: error: no matching function for call to ‘v8::Object::Get(const v8::Local<v8::String>&)’
 1879 |     return scope.Escape(New(persistentHandle)->Get(key));
      |                                                       ^
In file included from /home/trusktr/.node-gyp/14.15.5/include/node/node.h:67,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
 3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
 3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
In file included from ../src/binding.cpp:1:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(uint32_t) const’:
../../nan/nan.h:1884:57: error: no matching function for call to ‘v8::Object::Get(uint32_t&)’
 1884 |     return scope.Escape(New(persistentHandle)->Get(index));
      |                                                         ^
In file included from /home/trusktr/.node-gyp/14.15.5/include/node/node.h:67,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
 3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
 3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
In file included from ../src/binding.cpp:1:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2208:7: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2208 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/10.2.0/cassert:44,
                 from /home/trusktr/.node-gyp/14.15.5/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:54,
                 from ../src/binding.cpp:1:
../../nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../../nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
   24 |     assert(persistent().IsNearDeath());
      |                         ^~~~~~~~~~~
In file included from ../../nan/nan.h:2698,
                 from ../src/binding.cpp:1:
../../nan/nan_object_wrap.h: In member function ‘void Nan::ObjectWrap::MakeWeak()’:
../../nan/nan_object_wrap.h:67:18: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘MarkIndependent’
   67 |     persistent().MarkIndependent();
      |                  ^~~~~~~~~~~~~~~
In file included from /usr/include/c++/10.2.0/cassert:44,
                 from /home/trusktr/.node-gyp/14.15.5/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:54,
                 from ../src/binding.cpp:1:
../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../../nan/nan_object_wrap.h:124:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
  124 |     assert(wrap->handle_.IsNearDeath());
      |                          ^~~~~~~~~~~
../src/binding.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE render(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cpp:285:80: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  285 | _queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../src/binding.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE render_file(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cpp:321:80: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  321 | _queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
../src/binding.cpp: At global scope:
/home/trusktr/.node-gyp/14.15.5/include/node/node.h:758:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/trusktr/.node-gyp/14.15.5/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/binding.cpp:359:1: note: in expansion of macro ‘NODE_MODULE’
  359 | NODE_MODULE(binding, RegisterModule);
      | ^~~~~~~~~~~
In file included from ../src/binding.cpp:1:
../../nan/nan.h: In instantiation of ‘void Nan::imp::SetMethodAux(T, v8::Local<v8::String>, v8::Local<v8::FunctionTemplate>, ...) [with T = v8::Local<v8::Object>]’:
../../nan/nan.h:2394:20:   required from ‘void Nan::SetMethod(HandleType<T>, const char*, Nan::FunctionCallback) [with T = v8::Object; HandleType = v8::Local; Nan::FunctionCallback = void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)]’
../src/binding.cpp:351:42:   required from here
../../nan/nan.h:2378:12: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>)’
 2378 |   recv->Set(name, GetFunction(tpl).ToLocalChecked());
      |   ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/trusktr/.node-gyp/14.15.5/include/node/node.h:67,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/trusktr/.node-gyp/14.15.5/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
make: *** [binding.target.mk:131: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/trusktr/src/cruise-automation+webviz/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/trusktr/src/cruise-automation+webviz/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.105-1-MANJARO
gyp ERR! command "/home/trusktr/.n-node-versions/bin/node" "/home/trusktr/src/cruise-automation+webviz/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/trusktr/src/cruise-automation+webviz/node_modules/node-sass
gyp ERR! node -v v14.15.5
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
```

</details>

**Comment by jhurliman** [comment]
See https://github.com/cruise-automation/webviz/pull/585
